### ISSUE TITLE
如果我想要获得其它网站的host，我该怎么修改？

### ISSUE THREAD

**Issue by xiulou23** [Clov614/SteamHostSync#4]
我想要获得除了Github steam等等之外的网站的host，来加速访问，请问我应该怎么修改？你的项目能满足我这个需求吗？

**Comment by Clov614** [comment]
@xiulou23 fork 本仓库，修改 source.yaml

**Comment by xiulou23** [comment]
> @xiulou23 fork 本仓库，修改 source.yaml

多谢，我已经复制了。然后下面图中我想改成我的账户名与项目名，该怎么做。我改了readme后一运行项目又恢复原状了
![image](https://github.com/user-attachments/assets/b243d484-68a0-4069-894d-c5607aa69e8d)

**Comment by Clov614** [comment]
> > @xiulou23 fork 本仓库，修改 source.yaml
> 
> 多谢，我已经复制了。然后下面图中我想改成我的账户名与项目名，该怎么做。我改了readme后一运行项目又恢复原状了 ![image](https://private-user-images.githubusercontent.com/133690386/365946532-b243d484-68a0-4069-894d-c5607aa69e8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTUyODksIm5iZiI6MTcyNTk1NDk4OSwicGF0aCI6Ii8xMzM2OTAzODYvMzY1OTQ2NTMyLWIyNDNkNDg0LTY4YTAtNDA2OS04OTRkLWM1NjA3YWE2OWU4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwNzU2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjM2MTM4YWVkMTZiYTA2MzM1NjkxNmQ1NjQ5NTNlMDMxNTUyNzhkMDBkMDA4NzUzZTY4NDA2YWI1NWE1YjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4aWTprvl0w6WYEu7hpkp1AV6a5uXjrAF6-IL3j37NVE)

需要改项目中 main.go 对应位置字符串

**Comment by xiulou23** [comment]
> > > @xiulou23 fork 本仓库，修改 source.yaml
> > 
> > 多谢，我已经复制了。然后下面图中我想改成我的账户名与项目名，该怎么做。我改了readme后一运行项目又恢复原状了 ![image](https://private-user-images.githubusercontent.com/133690386/365946532-b243d484-68a0-4069-894d-c5607aa69e8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTUyODksIm5iZiI6MTcyNTk1NDk4OSwicGF0aCI6Ii8xMzM2OTAzODYvMzY1OTQ2NTMyLWIyNDNkNDg0LTY4YTAtNDA2OS04OTRkLWM1NjA3YWE2OWU4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwNzU2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjM2MTM4YWVkMTZiYTA2MzM1NjkxNmQ1NjQ5NTNlMDMxNTUyNzhkMDBkMDA4NzUzZTY4NDA2YWI1NWE1YjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4aWTprvl0w6WYEu7hpkp1AV6a5uXjrAF6-IL3j37NVE)
> 
> 需要改项目中 main.go 对应位置字符串

多谢，已搞定
