### ISSUE TITLE
你好，我有个关于readme文件的问题需要问一下

### ISSUE THREAD

**Issue by Shura23** [Clov614/SteamHostSync#5]
打扰了，之前我想要修改readme文件，问你应该去哪修改，你说是去main.go，然后我改成功了，但是我现在又想要改readme的其它地方，但是我没找到应该在main.go的哪里修改，我是否还要去main.go中改，图中圈起来的部分就是我想要修改的，但是项目自动执行后又恢复原状。我加了许多域名到我项目，不仅是加速steam和GitHub，所以想要修改readme中的介绍。
![image](https://github.com/user-attachments/assets/3e501f19-d661-4d83-af47-692c42946b3e)
![image](https://github.com/user-attachments/assets/c4202795-8702-4b4f-9bff-6a9661a30d22)

**Comment by Clov614** [comment]
readme_temp

**Comment by xiulou23** [comment]
> readme_temp
是指这一个吗
![image](https://github.com/user-attachments/assets/f10ace76-7f4c-4da3-9bea-603275aa464a)

**Comment by Clov614** [comment]
不是，是 README_TEMP  根目录普通文件

**Comment by xiulou23** [comment]
> 不是，是 README_TEMP 根目录普通文件

多谢，已搞定
