### ISSUE TITLE
【功能请求】添加GOG GALAXY hosts

### ISSUE THREAD

**Issue by MeowCold** [Clov614/SteamHostSync#6]
希望添加GOG GALAXY hosts，gog现在客户端不开加速器无法登陆

**Comment by Clov614** [comment]
@MeowCold 
![image](https://github.com/user-attachments/assets/7f9fdf3f-9dc3-4b51-9852-c6f073876b5b)
添加上了，粗鲁的抓包，可能有漏

**Comment by MeowCold** [comment]
感谢
